### ISSUE TITLE
Java 7 or 8?

### ISSUE THREAD

**Issue by bjornoss** [synapticloop/backblaze-b2-java-api#1]
Hi. 
First of all, thanks for creating this project. 

I tried to use the latest released jars in my Java 7 project but got a ClassNotFoundException:
Caused by: java.lang.ClassNotFoundException: java.util.Base64

java.util.Base64 was added in Java 8.

In the gradle file you specify sourceCompatibility = 1.7

I expect that you want to use the Base64 class from commons-codec lib?

My question is does this project requires Java 7 or 8?

Thanks.

**Comment by synapticloop** [comment]
Hello,

You're more than welcome, I am glad that it is finding some usage out there.

I aimed for  Java 7 - which I have now fixed - this was due to both the Mac build machine not having the 1.7 JDK installed and travis-ci pointing to oraclejdk8.

Thank you for the issue.

Regards
