### ISSUE TITLE
Large file support

### ISSUE THREAD

**Issue by dkocher** [synapticloop/backblaze-b2-java-api#11]
[Large Files, which will support storing files up to 1TB. This service is not yet available, and is subject to change.](https://www.backblaze.com/b2/docs/large_files.html)

**Comment by synapticloop** [comment]
Yes, the code was started - but there were too many un-answered questions - so waiting for now...

**Comment by dkocher** [comment]
I will resurrect a branch from commit 8f3013a.

**Comment by dkocher** [comment]
Parse minimum part size in authentication response in 5047b8b661aa8e68dc53374fd030d053286428e9.

**Comment by dkocher** [comment]
Works is in this [branch](https://github.com/iterate-ch/backblaze-b2-java-api/tree/feature/large-file-support).

**Comment by dkocher** [comment]
Merged in 946180d28081ff7e0c75fb12c973578107add722.
