### ISSUE TITLE
Remove prefix from version

### ISSUE THREAD

**Issue by dkocher** [synapticloop/backblaze-b2-java-api#15]
Any reason there is a `v` prefix in the version.

**Comment by synapticloop** [comment]
Went with the github suggestion of:

**Tagging suggestions**

It’s common practice to prefix your version names with the letter v. Some good tag names might be v1.0 or v2.3.4.

however in hindsight it is now causing more troubles than it is worth - I am updating my projects to remove the `v` classifier.

**Comment by dkocher** [comment]
At least it is uncommon for Maven artifacts and I don't know if the maven-release plugin can handle it to auto increment versions.

**Comment by synapticloop** [comment]
done
