### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by dkocher** [synapticloop/backblaze-b2-java-api#3]
Can you please clarify on the license.

**Comment by synapticloop** [comment]
MIT license

In a nutshell - do whatever you want - with attribution - will update the source code

**Comment by synapticloop** [comment]
Are you looking to integrate with cyberduck/mountainduck?

**Comment by dkocher** [comment]
@synapticloop Indeed.

**Comment by dkocher** [comment]
@synapticloop Let me know if you are interested in pull requests. Currently working on https://github.com/synapticloop/backblaze-b2-java-api/compare/master...iterate-ch:master

**Comment by synapticloop** [comment]
absolutely interested in pull requests - have had a look at some of the commits - they are more than welcome
