### ISSUE TITLE
Warnings on file upload

### ISSUE THREAD

**Issue by tanyona** [synapticloop/backblaze-b2-java-api#40]
When uploading a file, the following warnings are logged

```
[WARN] 14-Oct-2018 20:22:51.223 | synapticloop.b2.response.B2AuthorizeAccountResponse - Found an unexpected key of 'allowed' in JSON that is not mapped to a field, with value '{"bucketName":null,"capabilities":["listKeys","writeKeys","deleteKeys","listBuckets","writeBuckets","deleteBuckets","listFiles","readFiles","shareFiles","writeFiles","deleteFiles"],"namePrefix":null,"bucketId":null}'.
[WARN] 14-Oct-2018 20:22:51.223 | synapticloop.b2.response.B2AuthorizeAccountResponse - Found an unexpected key of 'recommendedPartSize' in JSON that is not mapped to a field, with value '100000000'.
[WARN] 14-Oct-2018 20:22:51.224 | synapticloop.b2.response.B2AuthorizeAccountResponse - Found an unexpected key of 'absoluteMinimumPartSize' in JSON that is not mapped to a field, with value '5000000'.
```

Is it possible to have a setting/property not to warn on missed keys.

**Comment by jvtrigueros** [comment]
I believe these are new keys that aren't being accounted for by this library :(

**Comment by tanyona** [comment]
Indeed I had a look at the code and the "allowed" field isn't listed. The other two seem to be among expected fields - https://github.com/synapticloop/backblaze-b2-java-api/blob/master/src/main/java/synapticloop/b2/response/B2AuthorizeAccountResponse.java. Not sure why they are being included.

**Comment by tanyona** [comment]
Just realised that I'm using the 2.2.0 jar whose code may be different from the latest. That would explain the why.
