### ISSUE TITLE
Missing credentials in Travis CI enviroment

### ISSUE THREAD

**Issue by dkocher** [synapticloop/backblaze-b2-java-api#9]
Looks like the pull requests are failing due to missing credentials in the Travis CI environment.

**Comment by synapticloop** [comment]
Odd - credentials are there... There is a failing test B2DownloadFileReqyestTest which I have just fixed - will be pushing soon.

**Comment by dkocher** [comment]
I just read in the Travis CI documentation, that environment variables are not available for builds triggered by pull requests.

**Comment by dkocher** [comment]
You can check that the tests are green in our [fork](https://github.com/iterate-ch/backblaze-b2-java-api/branches).

**Comment by synapticloop** [comment]
removed pull request building from travis
